### ISSUE TITLE
command refreshusers

### ISSUE THREAD

**Issue by Wazarr94** [PassiveModding/ELO#11]
Hello, thanks for the bot, we use it a lot (2000+ games) and it's very appreciated.

Just a small request here, could you make a refreshusers command ? It would do the same as refreshuser, but for every user. Because when we reset leaderboards, we want to remove the ranks from everyone, and we didn't find a way to do so.

Thanks

**Comment by PassiveModding** [comment]
Hi, this command was removed due to causing instability with the bot. User's names will refresh automatically once they play a game or run the register command.
