### ISSUE TITLE
SetNicknameFormat

### ISSUE THREAD

**Issue by OoWonder** [PassiveModding/ELO#12]
Explanation is confusing. Was trying to set this up in a server when ran into a problem with the setnicknameformat command. The current command explanation is: "setnicknameformat ...format". - That's it. And it works, say if I do =setnicknameformat [0] user it will set that as the user. I think this is a question based around operations and not exactly code.

How do you setup this command in the discord so it sets a format that the bot follows and not a name that everyone who registers gets?
And when scoring games, when the points change how do you make the bot change the name of the user who's points have changed?

**Comment by torriz** [comment]
Did you check `=NicknameFormats`?
it's explained there.

Also, isn't this is more of a ELO support server (#support) issue/question than issue with the bot

**Comment by OoWonder** [comment]
Yes that worked thanks
